### PR TITLE
destroying nexus

### LINKED ISSUE #655: DESTROY THE NEXUS
(I snap assigned to @O-Susanoo as I assume he would get the most gratification out of any of us for destroying his no.1 rival)

### Description
The unanimous vote was: we can't stand the git submodule format as it is providing zero value and moderate headaches

---

### Deliverables
- MAKE THE MONOREPO A TRUE MONOREPO
- REACTOR CONSUMES NEXUS LIKE AN AMOEBA
- 🔫 / RETIRE THE NEXUS REPO!

---

### Additional context
Images for reference:
image

image

### PR DESCRIPTION
**Pull request by O-Susanoo**
ezgif-7-98995cc353ef

i suggest that once this one goes in , that you remove you reactor folder and clone a fresh new one so that you don't have issues with the already existing config of your git in case you don't want to do that then you can do the following 
```
- git checkout master
- rm -rf  src/nexus/
edit this file .git/config and remove these lines

[submodule "src/nexus"]
        url = git@github.com:ospin-web-dev/nexus.git

i think you could also remove these lines

[submodule]
	active = .
(but not really sure)

- git pull
```

and you should be fine , after that whatever branch you are on it just checkout that branch remove the nexus folder if it's there and git rebase master

closes #655

### CODE REVIEW

**Comment by ConorTighe1995** [comment]
Is this WIP? Just wondering because its still nested in the repo, think you have to git rm it:
https://github.com/ospin-web-dev/REACTor/tree/master/src

Also loving the fatality

**Comment by ConorTighe1995** [comment]
Lloving the fatality.

**Comment by O-Susanoo** [comment]
thank you @ConorTighe1995 for taking the time to testing it

**Comment by O-Susanoo** [comment]
ok will do , do you think that you should merge first or i should ? i don't want to cause you any weird conflicts ?

**Comment by DanielSeehausen** [comment]
didn't mean to close - reopening and moving to a WIP

**Comment by O-Susanoo** [comment]
i kept the test folder of nexus inside nexus what do you guys think about that ?

**Comment by DanielSeehausen** [comment]
> i kept the test folder of nexus inside nexus what do you guys think about that ?

i'd vote move to follow the pattern in the repo (no test files within `src/`) for:
- standardization/user expectations
- file pathing


`test/src/nexus/*`

**Comment by O-Susanoo** [comment]
done

**Pull request merged**
